Fixed Dockerfile and addon config

diff --git a/amr2mqtt/Dockerfile b/amr2mqtt/Dockerfile
--- a/amr2mqtt/Dockerfile
+++ b/amr2mqtt/Dockerfile
@@ -6,16 +6,15 @@ FROM alpine:3.22.0 as build_rtlamr
 # https://github.com/bemasher/rtlamr/releases
 ENV RTLAMR_VERSION 0.9.1
 
-RUN set -eux; \
-    apk update; \
-    apk add --no-cache --virtual .build-deps tar curl;
-    APKARCH="$(apk --print-arch)"; \
-    case "${APKARCH}" in \
+RUN set -eux && apk update && apk add --no-cache --virtual .build-deps tar curl && \
+    ARCH=$(apk --print-arch) && \
+    echo "Running on architecture: $ARCH" && \
+    case "${ARCH}" in \
         x86_64)  BINARCH='amd64' ;; \
         armhf)   BINARCH='arm' ;; \
         armv7)   BINARCH='arm' ;; \
         aarch64) BINARCH='arm64' ;; \
-        *) echo >&2 "error: unsupported architecture (${APKARCH})"; exit 1 ;; \
+        *) echo >&2 "error: unsupported architecture (${ARCH})"; exit 1 ;; \
     esac; \
     curl -J -L -o /tmp/rtlamr.tar.gz \
     "https://github.com/bemasher/rtlamr/releases/download/v${RTLAMR_VERSION}/rtlamr_linux_${BINARCH}.tar.gz"; \
